config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get    '/about',    to: 'static_pages#about'
  get    '/signup',   to: 'users#new'
  post   '/signup',   to: 'users#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users
  resources :posts, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :posts
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 22 },
                    uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  
  def index
    @post = Post.new
    @posts = Post.paginate(:page => params[:page], :per_page => 4).order('created_at DESC')
  end

  def create
    user = User.find_by(id: session[:user_id])
    @post = user.posts.build(post_params)
    if @post.save
      flash[:success] = "Your post has been created."
      redirect_to root_url
    else
      flash[:danger] = "Error! Your post has not been created."
      redirect_to root_url
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :not_logged_in, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

    def not_logged_in
      if logged_in?
        redirect_to root_url
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :not_logged_in,  only: [:new, :create]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      remember @user
      flash[:success] = "Welcome to Members-Only!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation,
                                   :avatar_src)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def not_logged_in
      if logged_in?
        redirect_to root_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Members-Only!"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
require 'faker'

  # Generate an avatar picture.
  def generate_avatar
    Faker::Avatar.image("#{SecureRandom.urlsafe_base64}", "150x150", "jpg", "set4", "bg2")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication" target="_blank" rel="noopener">Project: Members-only!</a>
    by <a href="https://github.com/AlexRobi" target="_blank" rel="noopener">Alexis Robillart</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-info">
  <div class="container">
    <%= link_to 'Members-Only!', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(about_path) %>">
          <%= link_to 'About', about_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %> 
              <img class="avatar rounded-circle" src="<%= current_user.avatar_src %>" />
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", current_user, class: "dropdown-item" %>
              <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item <%= 'active' if current_page?(login_path) %>">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(signup_path) %>">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "mt-3 alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<% provide(:title, "Home") %>

<div class="mt-3">
  <% if logged_in? %>
    <div>
      <%= form_for(@post) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control", placeholder: "What's up?" %>
        </div>
        
        <%= f.submit "Create a post", class: "btn btn-info btn-block" %>
      <% end %>
    </div>
  <% else %>
    You must be <%= link_to "logged in", login_path %> to post.
  <% end %>
</div>

<h1 class="text-center my-3 h1-pi">Recent posts</h1>

<%= will_paginate(@posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

  <% @posts.each do |post| %>
    <div class="card border-info mb-3">
      <div class="card-header">
      <% if logged_in? %>
        <img class="avatar" src="<%= (post.user.avatar_src) unless post.user.nil? %>" />
        <%= (link_to post.user.name, post.user, class: "name-pi") unless post.user.nil? %>
      <% else %>
        [<%= link_to "Log in", login_path %> to see the author name.]
      <% end %>
      </div>
      <div class="card-body text-info">
        <p class="card-text"><%= post.content %></p>
          <p class="card-text">
            <small class="text-muted">
              Created <%= time_ago_in_words(post.created_at) %> ago. 
            </small>
          </p>
      </div>
    </div>
  <% end %>

<%= will_paginate(@posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1 class="text-center my-4">About this app</h1>
<p>This is the <a href="https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication"
   target="_blank" rel="noopener">Project 2: Members-only!</a> from the 
   Ruby on Rails curriculum of <a href="https://www.theodinproject.com/" target="_blank">
   The Odin Project</a>.
</p>
<h5>Assignement:</h5>
<blockquote class="blockquote">
  In this project, you’ll be building an exclusive clubhouse 
  where your members can write embarrassing posts about non-members. 
  Inside the clubhouse, members can see who the author of a post is but, 
  outside, they can only see the story and wonder who wrote it.
</blockquote>
<p>You can view the source code of the app on 
<a href="https://github.com/AlexRobi/members-only" target="_blank">GitHub</a>.

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages' %>

  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>
  
  <div class="form-group">
    <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  
  <div class="form-group">
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>

  <% if @user.avatar_src.nil? %>
    <%= f.hidden_field :avatar_src, value: generate_avatar %>
  <% end %>

  <div class="form-group">
  <%= f.password_field :password_confirmation, class: "form-control", 
                        placeholder: "Password confirmation" %>
  </div>
  
  <%= f.submit yield(:button_text), class: "btn btn-info btn-block" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Settings") %>
<% provide(:button_text, 'Save changes') %>
<% provide(:url, user_path) %>

<div class="mx-auto col-12 col-md-10 col-lg-8">

  <h1 class="my-4 text-center">Update your profile</h1>

  <%= render 'users/form' %>
  <div class="my-3">
    <img class="mb-1" src="<%= @user.avatar_src %>" />
    <%= form_for(@user) do |f| %>
      <%= f.hidden_field :avatar_src, value: generate_avatar %>
      <%= f.submit 'Generate a new avatar' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% provide(:url, signup_path) %>

<div class="mx-auto col-12 col-md-10 col-lg-8">

  <h1 class="text-center my-4">Sign up</h1>

  <%= render 'users/form' %>

  <p class="my-2">Already have an account? <%= link_to "Log in.", login_path %></p>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="text-center mt-4"><img class="avatar-us" src="<%= @user.avatar_src %>" /></div>
<h1 class="text-center h1-us"><%= @user.name %></h1>
<h5 class="text-center mb-3 h1-us"><%= pluralize(@user.posts.count, 'post') %></h5>

<% @user.posts.all.each do |post| %>
  <div class="card border-info mb-3">
    <div class="card-header">
      <img class="circle-rounded avatar" src="<%= post.user.avatar_src %>" />
      <%= (link_to post.user.name, post.user) unless post.user.nil? %>
    </div>
    <div class="card-body text-info">
      <p class="card-text"><%= post.content %></p>
        <p class="card-text">
          <small class="text-muted">
            Created <%= time_ago_in_words(post.created_at) %> ago. 
          </small>
        </p>
    </div>
  </div>
<% end %>